import { useEffect, useState } from "react";
import { DriveImage } from "../DriveImage";
import type { Post, SiteContent } from "@tpb/contracts";
import { api } from "../../lib/api";
import { CollectionState, formatDate } from "./ui";

export function News({ news, anchor = "berita" }: { news: SiteContent["news"]; anchor?: string }) {
  const [posts, setPosts] = useState<Post[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [active, setActive] = useState<Post | null>(null); const [tab, setTab] = useState("all");
  useEffect(() => { let alive = true; api.listPublic().then((items) => alive && setPosts(items)).catch((e: Error) => alive && setError(e.message)).finally(() => alive && setLoading(false)); return () => { alive = false; }; }, []);
  const categories = ["all", ...Array.from(new Set(posts.map((post) => post.category)))]; const shown = tab === "all" ? posts : posts.filter((post) => post.category === tab);
  return <section id={anchor} className="scroll-mt-24 bg-cream py-24"><div className="mx-auto max-w-[1360px] px-5 lg:px-10"><div className="reveal flex flex-wrap items-end justify-between gap-6"><div><span className="font-mono text-[11px] uppercase tracking-[0.3em] text-leaf-600">{news.kicker}</span><h2 className="mt-4 font-display text-4xl font-extrabold leading-tight text-midnight lg:text-5xl">{news.title}</h2></div><div className="flex flex-wrap gap-2">{categories.map((category) => <button key={category} onClick={() => setTab(category)} className={`rounded-full px-5 py-2.5 text-[13px] font-bold capitalize ${tab === category ? "bg-midnight text-white" : "border border-midnight/12 text-midnight/60"}`}>{category === "all" ? "Semua" : category}</button>)}</div></div><CollectionState loading={loading} error={error} empty={!shown.length}><div className="mt-12 grid gap-7 md:grid-cols-2 lg:grid-cols-3">{shown.map((post) => <article key={post.id} onClick={() => setActive(post)} className="reveal group flex cursor-pointer flex-col overflow-hidden rounded-3xl border border-midnight/8 bg-white transition hover:-translate-y-1.5"><div className="relative h-52 overflow-hidden bg-midnight/10">{post.image && <DriveImage src={post.image} alt={post.title} className="h-full w-full object-cover transition duration-700 group-hover:scale-105" />}<span className="absolute left-4 top-4 rounded-full bg-gold px-3 py-1 font-mono text-[10px] font-bold uppercase tracking-wider text-midnight">{post.category}</span></div><div className="flex flex-1 flex-col p-6"><div className="font-mono text-[11px] uppercase tracking-wider text-midnight/45">{formatDate(post.date)} · {post.readTime}</div><h3 className="mt-3 flex-1 font-display text-xl font-bold leading-snug text-midnight">{post.title}</h3><span className="mt-5 text-[13px] font-bold text-midnight/70">Selengkapnya →</span></div></article>)}</div></CollectionState></div>{active && <div onClick={() => setActive(null)} className="fixed inset-0 z-[90] grid place-items-center bg-midnight/70 p-4 backdrop-blur-sm"><div onClick={(event) => event.stopPropagation()} className="max-h-[85vh] w-full max-w-2xl overflow-auto rounded-3xl bg-white p-8"><div className="flex items-start justify-between gap-4"><div><span className="font-mono text-[11px] uppercase tracking-wider text-leaf-600">{active.category}</span><h3 className="mt-2 font-display text-3xl font-extrabold text-midnight">{active.title}</h3><p className="mt-2 text-xs text-midnight/50">{formatDate(active.date)} · {active.readTime}</p></div><button onClick={() => setActive(null)} aria-label="Tutup" className="rounded-full bg-midnight/5 px-3 py-1 text-sm font-bold text-midnight">✕</button></div>{active.image && <DriveImage src={active.image} alt={active.title} className="mt-6 max-h-72 w-full rounded-2xl object-cover" />}<p className="mt-6 whitespace-pre-line text-sm leading-relaxed text-midnight/75">{active.content || active.excerpt}</p></div></div>}</section>;
}

export function CTA({ cta, onDaftar, anchor }: { cta: SiteContent["cta"]; onDaftar: () => void; anchor?: string }) { return <section id={anchor} className="scroll-mt-24 bg-cream pb-24"><div className="mx-auto max-w-[1360px] px-5 lg:px-10"><div className="reveal relative overflow-hidden rounded-[2.5rem] bg-gradient-to-br from-leaf-600 via-leaf to-leaf-600 px-8 py-16 text-center lg:px-20"><h2 className="relative mx-auto max-w-2xl font-display text-4xl font-extrabold leading-tight text-white lg:text-5xl">{cta.title}</h2><p className="relative mx-auto mt-5 max-w-xl text-[16px] text-white/85">{cta.body}</p><div className="relative mt-9 flex flex-wrap justify-center gap-4"><button onClick={onDaftar} className="rounded-full bg-white px-8 py-4 text-sm font-extrabold text-leaf-600">{cta.primary}</button><a href={cta.secondaryHref} className="rounded-full border border-white/50 px-8 py-4 text-sm font-bold text-white">{cta.secondary}</a></div></div></div></section>; }

export function Footer({ footer }: { footer: SiteContent["footer"] }) {
  const [email, setEmail] = useState(""); const [status, setStatus] = useState<"idle" | "sending" | "sent" | "error">("idle");
  const subscribe = async (event: React.FormEvent) => { event.preventDefault(); if (!email.trim()) return; setStatus("sending"); try { await api.subscribe(email); setEmail(""); setStatus("sent"); } catch { setStatus("error"); } };
  const socials = [
    footer.socials.facebook ? { label: "Facebook", href: footer.socials.facebook } : null,
    footer.socials.twitter ? { label: "Twitter", href: footer.socials.twitter } : null,
    footer.socials.youtube ? { label: "YouTube", href: footer.socials.youtube } : null,
    footer.socials.linkedin ? { label: "LinkedIn", href: footer.socials.linkedin } : null,
  ].filter(Boolean) as { label: string; href: string }[];
  return <footer className="relative bg-midnight text-white"><div className="mx-auto grid max-w-[1360px] gap-14 px-5 py-20 lg:grid-cols-[1.6fr_1fr_1fr] lg:px-10"><div><h3 className="font-display text-3xl font-extrabold leading-tight">{footer.newsletterTitle}</h3><form onSubmit={subscribe} className="mt-7 flex max-w-md items-center rounded-full border border-white/15 bg-white/5 p-1.5"><input type="email" required aria-label="Alamat email untuk berlangganan" value={email} onChange={(event) => setEmail(event.target.value)} className="flex-1 bg-transparent px-5 py-2.5 text-sm text-white placeholder:text-white/40 focus:outline-none" /><button disabled={status === "sending"} className="rounded-full bg-gold px-6 py-2.5 text-xs font-extrabold text-midnight">{status === "sending" ? "…" : status === "sent" ? "Terkirim ✓" : status === "error" ? "Gagal ✕" : footer.submitLabel}</button></form>{socials.length > 0 && <div className="mt-5 flex flex-wrap gap-4 text-sm text-white/70">{socials.map((s) => <a key={s.href} href={s.href} target="_blank" rel="noreferrer" className="hover:text-white">{s.label}</a>)}</div>}<p className="mt-9 text-xs font-bold uppercase tracking-[0.2em] text-white/55">{footer.tagline}</p></div><div><h4 className="font-display text-xl font-bold">{footer.infoTitle}</h4><ul className="mt-6 space-y-4 text-sm text-white/70"><li>{footer.contact.phoneHref ? <a href={footer.contact.phoneHref} target="_blank" rel="noreferrer" className="hover:text-white">{footer.contact.phone}</a> : footer.contact.phone}</li><li>{footer.contact.email}</li><li>{footer.contact.address}</li></ul></div><div><h4 className="font-display text-xl font-bold">{footer.quickLinksTitle}</h4><ul className="mt-6 space-y-3.5 text-sm text-white/70">{footer.quickLinks.map((link) => <li key={`${link.label}-${link.href}`}><a href={link.href} className="hover:text-white">{link.label}</a></li>)}<li className="text-white/60">{footer.copyright}</li></ul></div></div></footer>;
}

export function BackToTop() { const [show, setShow] = useState(false); useEffect(() => { const onScroll = () => setShow(window.scrollY > 600); window.addEventListener("scroll", onScroll, { passive: true }); return () => window.removeEventListener("scroll", onScroll); }, []); return <button onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })} aria-label="Kembali ke atas" className={`fixed bottom-7 right-7 z-40 grid h-12 w-12 place-items-center rounded-full bg-gold text-midnight transition-all ${show ? "opacity-100" : "pointer-events-none opacity-0"}`}>↑</button>; }
